name: qrfinity
description: A new Flutter project for creating and scanning QR.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  hive: ^2.2.2
  ionicons: ^0.1.2
  get_it: ^7.2.0
  qr_flutter: ^4.0.0
  hive_flutter: ^1.1.0
  google_fonts: ^3.0.1
  mobile_scanner: ^2.0.0
  share_plus: ^4.0.9
  path_provider: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  hive_generator: ^1.1.3

flutter:
  uses-material-design: true